SET SQLBLANKLINES ON
CREATE VIEW CLIENT_TRADE_BY_MONTH
AS select first_name as "First name", last_name as "Last name", trade as "Total trade value [EUR]", yr as "Year", mnt as "Month"
  from clients left outer join 
    (select client_id as cid, sum(order_value) as trade, extract(year from date_ordered) as yr, extract(month from date_ordered) as mnt
        from orders
        group by (client_id, extract(year from date_ordered), extract(month from date_ordered)))
    on clients.client_id = cid;

CREATE VIEW CURRENT_PRICES
AS SELECT 
    products.name as "Products name", date_cr as "Valid since", tmp.ver as "Version no.", price as "Products price"
FROM
    products join (select max(date_created) as date_cr, max(version) as ver, product_id as prod_id, price from product_versions group by product_id, price) tmp
    on products.product_id = prod_id;

CREATE VIEW HIGHEST_GAIN_PRODUCTS
AS select max(gain) as "Maximal gain", "Year", "Month", max(prod_id) as "Products ID"
from (select order_items.product_id as prod_id, sum(product_versions.price * order_items.products_count) as gain, extract(year from orders.date_ordered) as "Year", extract(month from orders.date_ordered) as "Month"
    from order_items 
        join product_versions on order_items.product_id = product_versions.product_id
        join orders on order_items.order_id = orders.order_id
    group by order_items.product_id, extract(year from orders.date_ordered), extract(month from orders.date_ordered))
group by "Year", "Month"
order by "Year" desc, "Month" desc;

COMMENT ON TABLE CLIENT_TRADE_BY_MONTH IS 'Income generated by each client per month.';

COMMENT ON TABLE CURRENT_PRICES IS 'Current prices of each product.';

COMMENT ON TABLE HIGHEST_GAIN_PRODUCTS IS 'Products that generated the biggest income in each month.';
