stages:
  - deploy_db
  - feed_db
  - test_db

deploy:
  stage: deploy_db
  script:
    - echo "Deploying database..."
    - sqlplus64 $db_user/$db_password@ora1.elka.pw.edu.pl/iais @delete_tables.sql
    - sqlplus64 $db_user/$db_password@ora1.elka.pw.edu.pl/iais @kbd2a10_pr/database/KBD2A10/deploy_db.sql
    - sqlplus64 $db_user/$db_password@ora1.elka.pw.edu.pl/iais @kbd2a10_pr/database/KBD2A10/deploy_triggers.sql
    - sqlplus64 $db_user/$db_password@ora1.elka.pw.edu.pl/iais @kbd2a10_pr/database/KBD2A10/deploy_views.sql
  tags:
    - kbd-1

feed:
  stage: feed_db
  script:
    - echo "Feeding data into DB..."
    - sqlplus64 $db_user/$db_password@ora1.elka.pw.edu.pl/iais @feed_db.sql
  tags:
    - kbd-1

test:
  stage: test_db
  script:
    - echo "Testing DB..."
    - bash tests/adding_order.sh
  tags:
    - kbd-1
