stages:
  - deploy_db
  - feed_db
  - test_db

deploy:
  stage: deploy_db
  script:
    - echo "Deploying database..."

  tags:
    - kbd-1

feed:
  stage: feed_db
  script:
    - echo "Feeding data into DB..."
  tags:
    - kbd-1

test:
  stage: test_db
  script:
    - echo "Testing DB..."
    - bash tests/adding_order.sh
  tags:
    - kbd-1
